### ISSUE TITLE
Opening links does not work

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Geary#2]
I get:

```
(geary:2): GLib-GIO-CRITICAL **: g_dbus_connection_signal_unsubscribe: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(geary:2): GLib-GIO-CRITICAL **: g_dbus_connection_signal_subscribe: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

Whenever I try to open a link in Geary. Nothing happens.

**Comment by TingPing** [comment]
You have `xdg-desktop-portal-gtk` installed?

**Comment by jurf** [comment]
Yes, `xdg-desktop-portal-gtk-0.7-1.fc26.x86_64`.

**Comment by mjog** [comment]
@jurf, thanks for reporting this issue.

Geary simply calls `gtk_show_uri()` to load links from emails and on my ubuntu system with xdg-desktop-portal-gtk 0.7 installed this works fine, so I'd suggest this is likely a system mis-configuration rather than a Geary bug.

As the GTK+ API docs for `gtk_show_uri[_on_window]()` states:

> The uri must be of a form understood by GIO (i.e. you need to install gvfs to get support for uri schemes such as http:// or ftp://, as only local files are handled by GIO itself).

Do you have GIO/GVFS installed as well?

**Comment by jurf** [comment]
@mjog thanks for responding. Yes, I have Fedora 26, full GNOME, though I have been getting crashes from the desktop portal. If it works for you then it’s a Fedora issue. I’ll close this.

**Comment by mjog** [comment]
No problem. If it does turn out to be a problem with Geary, feel free to reopen.

**Comment by TingPing** [comment]
For what its worth I've never had portal issues on F26 or F27.
