### ISSUE TITLE
Printing to file seems lack permissions

### ISSUE THREAD

**Issue by lunaryorn** [flathub/org.gnome.Geary#42]
I can't choose a file to save to when trying to print a mail to PDF:

![print dialog](https://user-images.githubusercontent.com/224922/104807638-a5bf4a80-57e0-11eb-9b90-bf60968d9d56.png)

Then save dialog seems to have no access to any directory:

![save dialog](https://user-images.githubusercontent.com/224922/104807645-b1127600-57e0-11eb-9c0d-ddeaaf627b15.png)

I worked around this by adding ~/Downloads access via flatseal, but in other flatpaks saving seems to working without this.

**Comment by mjog** [comment]
Hi, thanks for the bug report. Issues printing under Flatpak is [a known problem](https://gitlab.gnome.org/GNOME/geary/-/issues/562), however it is good to know that adding write permissions to Downloads will at least let that work. I'll look into adding that.

**Comment by lunaryorn** [comment]
Just to clarify, because my report may have been to brief: I don't actually want to print to a real printer (haven't tried and don't need to really).

I do want to print to PDF for archiving and I expected to be able to save the PDF at any place, e.g. like I can save a file to any place in libreoffice or inkscape flatpaks, and not just in those directories the Apps explicitly has write permissions for.

To that end adding write permissions to Downloads is a proper workaround for me, but I wonder why saving those work like in all other flatpaks.

**Comment by mjog** [comment]
Yes I understand, but the issue that prevents WebKitGTK from printing to a PDF anywhere on your file system is the same as the issue that prevents it from printing to actual printers - it's just not Flatpak portal aware. For example, Geary doesn't give RW access to anything (except ~/Downloads now) - but since it uses GTK file choosers that are portal-aware, email attachments can still be saved anywhere. It would be the same with WebKitGTK.

Adding support for writing to `~/Downloads` is just a convenient workaround for the moment.

**Comment by mjog** [comment]
The reason why it works for other applications under Flatpak is they are using GTK to print, which again is portal aware, so it works fine. Geary uses WebKitGTK to print, which for technical reasons doesn't use GTK's printing infrastructure, and to date has not been made compatible with portals.

There's nothing else that can be done about this from Geary's end until WebKitGTK adds this support.

**Comment by lunaryorn** [comment]
Thanks for taking the time to explain, and adding the workaround 🙏

**Comment by mjog** [comment]
No problem! :)
