### ISSUE TITLE
Silent crash at launch due to missing org.freedesktop.secrets provider

### ISSUE THREAD

**Issue by squircle** [flathub/org.gnome.Geary#49]
### How to reproduce the problem:

1. Install the Flatpak in a KDE Plasma environment (I used OpenSUSE Tumbleweed 20210508)
2. Attempt to run the Flatpak

### What happens:

Nothing. It tries to launch, shows up briefly in the taskbar, then closes with no error messages.

### Why:

KDE Plasma environments don't provide `org.freedesktop.secrets` by default, resulting in the following error when run in the terminal (`flatpak run org.gnome.Geary`):

`*[wrn] 20:56:31.0333 geary:application-client.vala:1001: Error creating controller: The name org.freedesktop.secrets was not provided by any .service files`

### Workaround:

Installing `gnome-keychain` fixes the problem. There may be other packages that fulfill the requirement too, but I only tested this one. It seems to me that this Flatpak needs another dependency on something that provides `org.freedesktop.secrets`. It may also be helpful for the upstream project to change the behaviour to show a visible error rather than silently terminating.

**Comment by mjog** [comment]
Hi, thanks for the bug report.

Geary uses libsecret for secure password storage, which in turn (under Flatpak) uses a portal to access a FDO Secret Service password store, such as is provided by gnome-keyring. This and other runtime requirements are [documented in the FAQ](https://wiki.gnome.org/Apps/Geary/FAQ#Not_running_GNOME_3.3F), but as runtime dependencies they are beyond anything Geary can enforce. As such, this is a packaging bug - if whichever portal your desktop is using requires a Secret Service store to be installed, the portal's package should depend on that.

We should probably do better than silently crashing however, and instead display an error message at least. That is covered by https://gitlab.gnome.org/GNOME/geary/-/issues/1030

Since there's nothing that can be done about either of those two things here, I'll close this issue, but encourage you to file a bug with your distro to ensure a FDO Secret Service is installed along with the portal. If you do, please link back to it here so others can find it. Cheers!

**Comment by squircle** [comment]
Thanks. Created [OpenSUSE bug 1186100](https://bugzilla.opensuse.org/show_bug.cgi?id=1186100).
