### ISSUE TITLE
Outgoing Email text input not "working" in Pop! OS

### ISSUE THREAD

**Issue by wesleybits** [flathub/org.gnome.Geary#8]
Pop! OS is a Ubuntu distribution that's handled by my laptop's manufacturer. It runs a tuned version of Gnome 3 and uses Geary as it's primary email application.

Current version of Geary I have (0.12-dev) does not let me focus on the Email body text input block when writing an outgoing email.

Please tell me what else you need to help debug this issue.

**Comment by mjog** [comment]
Hi, thanks for reporting this issue. A few points:

The version that Pop ships is long out of date, the current stable release is 0.12.2 and contains a large number of bug fixes compared to the 0.12-dev version you have. Can you please upgrade and see if this issue is still present? Some options for upgrading are noted on the [Geary wiki](https://wiki.gnome.org/Apps/Geary/GetIt), but the easiest will likely be to install it from Flathub.org.

If the bug still exists after upgrading to 0.12.2, can you please file a bug in Geary's bug tracker? Again, details about how to do this are on [Geary's wiki](https://wiki.gnome.org/Apps/Geary/ReportingABug). This repository is only for issues relating to Geary on Flathub.

Lastly, it might be worth filing a bug with Pop to ask them to update their Geary package, so that other Pop users also benefit.

Thanks!

**Comment by wesleybits** [comment]
Yeah, 0.12.2's email body input works fine.

Sorry for the noise. I'll go look around for more interesting problems to report.
